# baseURL = "/"
languageCode = "en"
title = "EDBTpedia"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
relativeURLs = true
googleAnalytics = "UA-37717223-8"

[params]
    title = "EDBTpedia"
    date = "2022-03-13"
    description = "EDBTpedia is a media placeholder for the scientific tutorials and other education seminars that the EDBT community has organised. EDBT is a strong supporter of Open Science which is why it is making every effort to make these videos open to the public."
    images = ["/images/social-share.jpg"]
    imagesDir = ""
    email = "contact@devfesttoulouse.fr"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = ""
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = "http://eepurl.com/dps1j5"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    jumbo = "/images/logos/edbt.png"
    header = "/images/logos/edbt.png"
    # footer = "/images/logos/edbt.png"

[menu]
# [[menu.main]]
#     identifier = "jobs"
#     name = "Jobs"
#     url = "https://jobs.devfesttoulouse.fr/"
#     weight = 200
#     external = true

[languages]
[languages.en]
    weight = 1
    languageName = "gb"

# [languages.fr]
#     weight = 2
#     languageName = "fr"

# [languages.fr.params]
#     description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
